#!/bin/sh

#PATHS
ROOT = .
BIN = $(ROOT)/bin 
INC = $(ROOT)/include 
OBJ = $(ROOT)/obj 
SRC = $(ROOT)/src 
TST = $(ROOT)/testes  




util.o: SRC/util.c 
	gcc -c SRC/util.c

shared.o: SRC/shared.c
	gcc -c SRC/shared.c